### ISSUE TITLE
How to explore priv/sec risks

### ISSUE THREAD

**Issue by samuelweiler** [w3c/inclusive-xr-workshop#5]
Given the analysis of privacy issues the Immersive Web Working Group has already made and the observation that assistive technologies often expose their users to additional fingerprinting, it might be worth having some discussions specific to privacy in the workshop, perhaps as level-setting?  I would want to see participants consider the additional privacy and security exposure these users face.  @michael-n-cooper

**Comment by LJWatson** [comment]
This is undoubtedly an important topic, and getting more important every day. Can you explain what you mean by "level setting" though?

**Comment by dontcallmedom** [comment]
I've proposed an addition to the CfP to that effect
