### ISSUE TITLE
Alternate titles

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/inclusive-xr-workshop#7]
Discussing with @LJWatson and @brewerj , we wanted to find a title that would:
* use the "inclusive design" phrase
* indicate the goal of influencing future standards
* relate to XR and Web

Here are a few proposals:
* Bringing Inclusive Design to XR standards for the Web
* Inclusive Design & Immersive Web standards
* Immersive and Inclusive XR standards for the Web
* Inclusive Design for Immersive Web standards
* Closing the Accessibility Gaps in Standards for Immersive Web (subtitle: Bringing Inclusive Design to XR on the Web)

Thoughts?

**Comment by LJWatson** [comment]
Thanks for the suggestions @dontcallmedom.

I really like:
>Inclusive Design & Immersive Web standards>
 
 

It's short and it gets all the right points across.

**Comment by brewerj** [comment]
Dom, thanks for suggestions. 

My favorite is just a word or two off from Leonie's; I like "Inclusive Design for Immersive Web standards" as I think it sounds just a bit stronger and/or more purposeful. 

- Judy

**Comment by LJWatson** [comment]
"Inclusive Design for Immersive Web standards" works too. Very happy to 
go with that.
